# The sequence of triangle numbers is generated by adding the natural numbers.
# So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first
# ten terms would be:

# 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

# Let us list the factors of the first seven triangle numbers:

#  1: 1
#  3: 1,3
#  6: 1,2,3,6
# 10: 1,2,5,10
# 15: 1,3,5,15
# 21: 1,3,7,21
# 28: 1,2,4,7,14,28

# We can see that 28 is the first triangle number to have over five divisors.

# What is the value of the first triangle number to have over five hundred
# divisors?

def divisor_count_of(n)
  result = 0

  1.upto(n/2) do |i|
    result += 1 if n%i == 0
  end

  result + 1
end

i = 1
found = false

while !found
  divisor_count = 0

  if i.even?
    divisor_count = divisor_count_of(i/2)*divisor_count_of(i + 1)
  else
    divisor_count =  divisor_count_of(i)*divisor_count_of((i + 1)/2)
  end

  if divisor_count > 500
    puts i*(i+1)/2
    found = true
  end

  i += 1
end